### ISSUE TITLE
需要開機可以自動執行

### ISSUE THREAD

**Issue by pondahai** [pondahai/MacroByte#9]

**Comment by FalconLee1011** [comment]
如果在/etc/rc.local增加command "python /root/pythonCode copy.py" 或是 直接增加一個init script 是不是可行(?

**Comment by pondahai** [comment]
要執行的對象應該是 /www/cgi-bin/monitor.py 至於要放哪裡 要再找一下

**Comment by pondahai** [comment]
已經解決
新增 /etc/init.d/mechacar
然後在 /etc/rc.d/ 新增 S99mechacar 軟連結到 上述檔案
